_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 55
                - 95
                - 96
                - 105
            "2":
                - 5
                - 53
                - 55
                - 95
                - 96
                - 105
            "3":
                - 14
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": darwin-arm64
